/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.CdastroDAO;
import DTO.CadastroDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLDataException;

/**
 *
 * @author Asus
 */
public class CadastroView_clinvet extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView_clinvet
     */
    public CadastroView_clinvet() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeTutor = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtFone = new javax.swing.JTextField();
        txtNomeAnimal = new javax.swing.JTextField();
        txtIdadeAnimal = new javax.swing.JTextField();
        txtServico = new javax.swing.JTextField();
        txtEmergencia = new javax.swing.JTextField();
        botaoCadastro = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultas_cadastradas = new javax.swing.JTable();
        pesquisarConsultas = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("ClinVet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Atendimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome do tutor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail tutor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefone do tutor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome do animal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Idade do animal");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Serviço desejado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nível de emergência");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(txtNomeTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 212, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 212, -1));
        getContentPane().add(txtFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 212, -1));
        getContentPane().add(txtNomeAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 212, -1));
        getContentPane().add(txtIdadeAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 212, -1));
        getContentPane().add(txtServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 212, -1));

        txtEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 212, -1));

        botaoCadastro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botaoCadastro.setForeground(new java.awt.Color(0, 153, 153));
        botaoCadastro.setText("Cadastrar");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 6, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/clinVetof.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        consultas_cadastradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(consultas_cadastradas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 290, 300));

        pesquisarConsultas.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pesquisarConsultas.setForeground(new java.awt.Color(0, 102, 102));
        pesquisarConsultas.setText("Atualizar ");
        pesquisarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("ClinVet");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Consultas Registradas");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergenciaActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        String nome_tutor,email_tutor,telefone_tutor,nome_animal,idade_animal, servico_desejado ,nivel_emergencia;
        
        nome_tutor = txtNomeTutor.getText();
        email_tutor = txtEmail.getText();
                telefone_tutor = txtFone.getText();
                nome_animal = txtNomeAnimal.getText();
                idade_animal = txtIdadeAnimal.getText();
                servico_desejado = txtServico.getText();
                nivel_emergencia = txtEmergencia.getText();
                
                CadastroDTO objcadastrodto = new  CadastroDTO();
                objcadastrodto.setNome_tutor(nome_tutor);
                objcadastrodto.setEmail_tutor(email_tutor);
                objcadastrodto.setTelefone_tutor(telefone_tutor);
                objcadastrodto.setNome_animal(nome_animal);
                objcadastrodto.setIdade_animal(idade_animal);
                objcadastrodto.setServico_desejado(servico_desejado);
                objcadastrodto.setNivel_emergencia(nivel_emergencia);
                
                CdastroDAO objcadastrodao = new CdastroDAO();
                objcadastrodao.cadastrarConsulta(objcadastrodto);
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void pesquisarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarConsultasActionPerformed
        listarValores();
    }//GEN-LAST:event_pesquisarConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView_clinvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView_clinvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView_clinvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView_clinvet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroView_clinvet().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCadastro;
    private javax.swing.JTable consultas_cadastradas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton pesquisarConsultas;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmergencia;
    private javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtIdadeAnimal;
    private javax.swing.JTextField txtNomeAnimal;
    private javax.swing.JTextField txtNomeTutor;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables

    private void listarValores(){
        try {
            CdastroDAO objcadastrodao = new CdastroDAO();
            
            DefaultTableModel model = (DefaultTableModel) consultas_cadastradas.getModel();
            model.setNumRows(0);
            
            ArrayList<CadastroDTO> lista = objcadastrodao.PesquisarConsultaCadastrada();
            
            for(int num =0; num<lista.size(); num++){
                model.addRow(new Object[]{
                    lista.get(num).getNome_tutor(),
                    lista.get(num).getEmail_tutor(),
                    lista.get(num).getTelefone_tutor(),
                    lista.get(num).getNome_animal(),
                    lista.get(num).getIdade_animal(),
                    lista.get(num).getServico_desejado(),
                    lista.get(num).getNivel_emergencia()
                   
                    
                });
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores"+ erro);
        }
    }
}
